# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
---
name: build-docker-image

"on":
  push:

jobs:
  prepare:
    runs-on: STM32

    steps:
      - uses: actions/checkout@v4

      - name: Install pipenv
        run: apt-get update && apt-get install -y pipenv

      - name: Install dependencies
        run: pipenv install --deploy

      - name: Clean images directory
        run: rm -rf images/

      - name: Generate matrix of Dockerfiles
        run: pipenv run python3 ./src/main.py

      - name: Commit generated Dockerfiles
        run: |
          git config user.name "Forgejo Actions"
          git config user.email "actions@forgejo.local"

          git add images/*

          if ! git diff --cached --quiet; then
            git commit -m "Auto-generate Dockerfiles"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi

  build:
    runs-on: STM32

    needs:
      - prepare

    strategy:
      matrix:
        file:
          - "images/fw-arm-none-eabi.base.Dockerfile"
          - "images/fw-arm-none-eabi.ci.Dockerfile"

    steps:
      - name: Install docker-cli
        run: |
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg \
              -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc

          tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF

          apt-get update
          apt-get install -y docker-ce-cli jq

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image name from Dockerfile name
        id: img
        run: |
          echo "matrix.file ${{ matrix.file }}"
          fname=$(basename "${{ matrix.file }}")
          image="${fname%.Dockerfile}"   # remove .Dockerfile
          echo "name=$image" >> $GITHUB_OUTPUT
          echo "Image ${{ matrix.file }} => name: $image"

      - name: Get commit hash for Dockerfile
        id: file_commit
        run: |
          commit=$(git log -n 1 --format=%h -- "${{ matrix.file }}")
          echo "commit=$commit" >> "$GITHUB_OUTPUT"
          echo "Dockerfile commit: $commit"

      - name: Define image repository
        id: image
        run: |
          echo "repo=${{ secrets.DOCKER_HUB_USERNAME }}/test" \
            >> "$GITHUB_OUTPUT"

      - name: Generate Docker tags
        id: tags
        run: |
          repo="${{ secrets.DOCKER_HUB_USERNAME }}/test"
          name="${{ steps.img.outputs.name }}"
          commit="${{ steps.file_commit.outputs.commit }}"

          echo "tags<<EOF" >> "$GITHUB_OUTPUT"
          echo "$repo:$name" >> "$GITHUB_OUTPUT"
          echo "$repo:$name-$commit" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Login to Container Registry
        env:
          DOCKER_CONFIG: ${{ runner.temp }}/docker
        uses: docker/login-action@v3
        with:
          # registry: harbor.tech-tales.blog
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push
        env:
          DOCKER_CONFIG: ${{ runner.temp }}/docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ matrix.file }}
          tags: ${{ steps.tags.outputs.tags }}

#             ${{ steps.image.outputs.repo }}:${{ steps.img.outputs.name }}
#             ${{ steps.image.outputs.repo }}:${{ steps.img.outputs.name }}-\
#             ${{ steps.file_commit.outputs.commit }}

#            ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ steps.img.outputs.name }}
#            ${{ secrets.DOCKER_HUB_USERNAME }}/test:${{ steps.img.outputs.name }}-${{ steps.file_commit.outputs.commit }}
