---
name: build-airflow-image

on:
  push:
#     tags:
#       - release-*
#     paths:
#       - images/test.Dockerfile

env:
  IMAGE_NAME: test
  IMAGE_PATH: images/${{ env.IMAGE_NAME }}.Dockerfile

jobs:
  prepare:
    runs-on: STM32
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - id: set-matrix
        run: |
          files=$(ls images/*.Dockerfile | jq -R . | jq -s .)
          echo "matrix={\"file\": $files}" >> "$GITHUB_OUTPUT"

  build:
    needs:
      - prepare

    runs-on: STM32

    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: Install docker-cli
        run: |
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg \
              -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc

          tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF

          apt-get update
          apt-get install -y docker-ce-cli

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - id: changed
        run: |
          files=$(git diff --name-only HEAD~1 HEAD | grep '\.Dockerfile$' || true)
          files=$(echo "$files" | jq -R . | jq -s .)
          echo "matrix={\"file\": $files}" >> $GITHUB_OUTPUT

      - name: Extract image name from Dockerfile name
        id: img
        run: |
          fname=$(basename "${{ matrix.file }}")
          image="${fname%.Dockerfile}"   # remove .Dockerfile
          echo "name=$image" >> $GITHUB_OUTPUT

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          #registry: harbor.tech-tales.blog
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ matrix.file }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.img.outputs.name }}:latest

#       - name: Build and Push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
#           context: .
#           file: ${{ env.IMAGE_PATH }}
