---
name: build-docker-image

on:
  push:
#     tags:
#       - release-*
#     paths:
#       - images/test.Dockerfile

env:
  IMAGE_NAME: test
  IMAGE_PATH: images/${{ env.IMAGE_NAME }}.Dockerfile

jobs:
  prepare:
    runs-on: STM32
    outputs:
      matrix: ${{ steps.gen.outputs.matrix }}

    steps:
      - uses: actions/checkout@v4

      - name: Generate matrix of Dockerfiles
        id: gen
        run: |
          python3 << 'EOF'
          import glob, json, os
        
          files = sorted(glob.glob("images/*.Dockerfile"))
          matrix = {"file": files}
        
          with open(os.environ["GITHUB_OUTPUT"], "a") as f:
              f.write(f"matrix={json.dumps(matrix)}\n")
          EOF

      - name: Use matrix
        run: |
          echo "Matrix = ${{ steps.gen.outputs.matrix }}"

  build:
    needs:
      - prepare

    runs-on: STM32

    strategy:
      matrix: ${{ fromJson(needs.prepare.outputs.matrix) }}

    steps:
      - name: Show matrix values
        run: |
          echo "Matrix file = ${{ matrix.file }}"

      - name: Install docker-cli
        run: |
          install -m 0755 -d /etc/apt/keyrings
          curl -fsSL https://download.docker.com/linux/debian/gpg \
              -o /etc/apt/keyrings/docker.asc
          chmod a+r /etc/apt/keyrings/docker.asc

          tee /etc/apt/sources.list.d/docker.sources <<EOF
          Types: deb
          URIs: https://download.docker.com/linux/debian
          Suites: $(. /etc/os-release && echo "$VERSION_CODENAME")
          Components: stable
          Signed-By: /etc/apt/keyrings/docker.asc
          EOF

          apt-get update
          apt-get install -y docker-ce-cli jq

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

#       - name: Get previous commit
#         id: changed
#         run: |
#             if git rev-parse HEAD^ >/dev/null 2>&1; then
#               prev=HEAD^
#             else
#               # No parent commit — empty list
#               echo 'matrix={"file": []}' >> $GITHUB_OUTPUT
#               exit 0
#             fi

      - name: Extract image name from Dockerfile name
        id: img
        run: |
          fname=$(basename "${{ matrix.file }}")
          image="${fname%.Dockerfile}"   # remove .Dockerfile
          echo "name=$image" >> $GITHUB_OUTPUT
          echo "Image ${{ matrix.file }} => name: $image"

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          # registry: harbor.tech-tales.blog
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        
      - name: Show Dockerfile being used
        run: cat ${{ matrix.file }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: ${{ matrix.file }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.img.outputs.name }}:latest

#       - name: Build and Push
#         uses: docker/build-push-action@v6
#         with:
#           push: true
#           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.extract_tag.outputs.tag }}
#           context: .
#           file: ${{ env.IMAGE_PATH }}
