# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
---
name: build-docker-image

"on":
  push:

jobs:
  prepare:
    runs-on: STM32
    outputs:
      dockerfiles: ${{ steps.images_list.outputs.files }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pipenv
        run: apt-get update && apt-get install -y pipenv jq

      - name: Install dependencies
        run: pipenv install --deploy

      - name: Clean images directory
        run: rm -rf images/

      - name: Generate matrix of Dockerfiles
        run: pipenv run python3 ./src/main.py

      - name: List generated Dockerfiles
        id: images_list
        run: |
          files=$(printf '"%s"\n' images/*.Dockerfile | jq -R . | jq -s .)
          {
            echo "files<<EOF"
            echo "$files"
            echo "EOF"
          } >> "$FORGEJO_OUTPUT"
          cat "$FORGEJO_OUTPUT"

      - name: Commit generated Dockerfiles
        run: |
          git config user.name "Forgejo Actions"
          git config user.email "actions@forgejo.local"

          git add images/*.Dockerfile

          if ! git diff --cached --quiet; then
            git commit -m "Auto-generate Dockerfiles"
            git push origin HEAD
          else
            echo "No changes to commit"
          fi


  build:
    runs-on: host

    needs:
      - prepare

    strategy:
      matrix:
        # file: ${{ fromJSON(needs.prepare.outputs.dockerfiles) }} not working
        name: ["fw-arm-none-eabi"]
        variant: [base, ci]

    steps:
      - name: Debug matrix
        run: |
          echo "matrix.name=${{ matrix.name }}"
          echo "matrix.variant=${{ matrix.variant }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get commit hash for Dockerfile
        id: file_commit
        run: |
          set -e

          file="images/${{ matrix.name }}.${{ matrix.variant }}.Dockerfile"

          file_commit=$(git log -n 1 --format=%H -- "$file")
          branch_head=$(git rev-parse HEAD)
          branch_name="$FORGEJO_REF_NAME"

          if [ "$file_commit" = "$branch_head" ]; then
            is_latest=true
          else
            is_latest=false
          fi

          echo "file_commit=$file_commit" >> "$FORGEJO_OUTPUT"
          echo "branch_name=$branch_name" >> "$FORGEJO_OUTPUT"
          echo "is_latest=$is_latest" >> "$FORGEJO_OUTPUT"
          echo "dockerfile=$file" >> "$FORGEJO_OUTPUT"

          echo "Dockerfile commit : $file_commit"
          echo "Branch head       : $branch_head"
          echo "Branch            : $branch_name"
          echo "Is latest         : $is_latest"

      - name: Set image tags
        id: img
        run: |
          variant="${{ matrix.variant }}"
          branch_head=$(git rev-parse HEAD)
          repo="${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.name }}"
          commit="${{ steps.file_commit.outputs.file_commit }}"
          latest=''

          if [ ${{ steps.file_commit.outputs.is_latest }} = 'true' ]; then
              latest="$repo:${variant}-latest"
          fi

          {
            echo "tags<<EOF"
            echo "$repo:${variant}"
            echo "$repo:${variant}-$FORGEJO_REF_NAME"
            echo "$repo:${variant}-$commit"
            echo "$latest"
            echo "EOF"
          } >> $FORGEJO_OUTPUT
          cat "$FORGEJO_OUTPUT"

      - name: Login to Docker Hubs
        env:
          DOCKER_CONFIG: ${{ runner.temp }}/docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build & Push image
        env:
          DOCKER_CONFIG: ${{ runner.temp }}/docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ steps.file_commit.outputs.dockerfile }}
          push: true
          tags: ${{ steps.img.outputs.tags }}
