# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause.txt
---

on:
  push:

jobs:
  pytest:
    runs-on: STM32
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Install pipenv
        run: apt-get update && apt-get install -y pipenv

      - name: Install dependencies
        run: pipenv install --deploy --dev

      - name: Run CI tests
        run: pipenv run python ./tools/test_ci.py
