# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Generated by src/main.py from config/default/config.yaml.
# Do not edit by hand: edit ressources/templates/ and regenerate.
#
# image    : fw-arm-none-eabi-13.2.rel1
# variant  : ci
# features : locale -> build -> python -> uv -> arm-13.2.rel1 -> ci-runtime

FROM debian:trixie-slim

# -------------------------------------------------------------------
# feature: locale
# -------------------------------------------------------------------
# Kept first in every variant of every image: it is the layer all the images
# share, so it must be identical everywhere.
RUN apt-get update && apt-get install -y --no-install-recommends \
        locales \
    && sed -i \
        -e '/en_US.UTF-8/s/^# //g' \
        -e '/fr_FR.UTF-8/s/^# //g' \
        /etc/locale.gen \
    && locale-gen \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# -------------------------------------------------------------------
# feature: build
# -------------------------------------------------------------------
# make, cmake and ninja are carried by every firmware variant, including the
# ones that do not use them: a few tens of MB against the 1.2 GB toolchain,
# not worth a separate variant.
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        ninja-build \
        git \
        wget \
        bzip2 \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: python
# -------------------------------------------------------------------
# The system interpreter, for scripts that expect /usr/bin/python3. Project
# environments are uv's job, hence no pip and no pipenv here.
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: uv
# -------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# wget, not curl: curl is only present in the dev variant. Piping the
# installer into sh would also hide a download failure, so download it, run
# it, then check that uv really is there.
RUN wget -qO /tmp/uv-install.sh https://astral.sh/uv/install.sh \
    && env UV_INSTALL_DIR=/usr/local/bin UV_NO_MODIFY_PATH=1 \
        sh /tmp/uv-install.sh \
    && rm /tmp/uv-install.sh \
    && uv --version

# -------------------------------------------------------------------
# feature: arm-none-eabi
# -------------------------------------------------------------------
# The expensive layer, 1.2 GB. It must stay after every feature it shares
# with the other variants, otherwise it is stored once per variant.
ARG ARM_TOOLCHAIN_VERSION=13.2.rel1
ARG ARM_DL_LINK=https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/${ARM_TOOLCHAIN_VERSION}/binrel/arm-gnu-toolchain-${ARM_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi.tar.xz

ENV ARM_TOOLCHAIN_DIR=/opt/gnu_arm/${ARM_TOOLCHAIN_VERSION}
ENV PATH=${ARM_TOOLCHAIN_DIR}/bin:$PATH
ENV AM_I_IN_A_DOCKER_CONTAINER=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        xz-utils \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${ARM_TOOLCHAIN_DIR} /tmp/arm-toolchain \
    && wget -qO- ${ARM_DL_LINK} | tar -xJ -C /tmp/arm-toolchain --strip-components=1 \
    && mv /tmp/arm-toolchain/* ${ARM_TOOLCHAIN_DIR} \
    && rm -rf /tmp/arm-toolchain

ENV TOOLCHAIN_DEVCONTAINER_DIR=${ARM_TOOLCHAIN_DIR}

# -------------------------------------------------------------------
# feature: ci-runtime
# -------------------------------------------------------------------
# What the Forgejo runner needs to execute a job inside this image, not what
# the projects need to build. The runner runs the JavaScript actions
# (actions/checkout and friends) with the node of the container, and clones
# over ssh, hence node, git and openssh-client.
# `file` is there for libmagic: reuse depends on it, and a REUSE lint is a CI
# job like any other.
RUN apt-get update && apt-get install -y --no-install-recommends \
        nodejs \
        npm \
        git \
        openssh-client \
        curl \
        ca-certificates \
        file \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# provenance
# -------------------------------------------------------------------
# Kept last in every image: IMAGE_COMMIT changes at every build, and an ARG
# read by a RUN invalidates that layer and everything after it. Last means
# the only rebuilt layer is this one, a few bytes.
#
# Written to a file, not only to a LABEL: a job running inside the container
# can read a file, it cannot read the labels of its own image. This is what
# makes a floating tag traceable -- the log of a green run says exactly which
# commit to pin when that build has to be rolled back to.
#
# /etc/image-info, and the shape of os-release and machine-info: quoted
# KEY="value" lines, so the file is both readable with `cat` and sourceable
# with `. /etc/image-info`. Not /etc/*-release, which is the legacy
# distro-identification pile os-release was written to replace, and not
# os-release itself -- that is a symlink into /usr/lib owned by the base
# distribution, and appending to it means either editing the vendor's file or
# breaking the link.
#
# The keys are prefixed. A bare COMMIT= would collide with a local of whatever
# script sources this. IMAGE_ID and IMAGE_VERSION are avoided on purpose: they
# are os-release spec names with defined meanings, and borrowing them for
# something else is worse than not using them.
ARG IMAGE_COMMIT=unknown
# The commit's own date, RFC 3339, not the build time -- a build time would
# change on every rebuild and destroy the property IMAGE_COMMIT exists for.
# It is here because a hash has no order: it answers "which build is this",
# never "is this older than what I have pinned". The image tag carries the
# same date in its compact YYYYMMDD form, which is what makes two pins
# comparable by eye; this one is the full value, so that
# org.opencontainers.image.created below is what the OCI spec says it is.
ARG IMAGE_DATE=unknown
LABEL org.opencontainers.image.revision="$IMAGE_COMMIT"
LABEL org.opencontainers.image.created="$IMAGE_DATE"
RUN printf 'IMAGE_NAME="%s"\nIMAGE_VARIANT="%s"\nIMAGE_COMMIT="%s"\nIMAGE_DATE="%s"\n' \
        'fw-arm-none-eabi-13.2.rel1' 'ci' "$IMAGE_COMMIT" "$IMAGE_DATE" \
        > /etc/image-info
