# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Generated by src/main.py from config/default/config.yaml.
# Do not edit by hand: edit ressources/templates/ and regenerate.
#
# image    : fw-arm-none-eabi-13.2.rel1
# variant  : dev-jlink
# features : locale -> build -> python -> uv -> arm-13.2.rel1 -> ci-runtime -> dev -> jlink

FROM debian:trixie-slim

# -------------------------------------------------------------------
# feature: locale
# -------------------------------------------------------------------
# Kept first in every variant of every image: it is the layer all the images
# share, so it must be identical everywhere.
RUN apt-get update && apt-get install -y --no-install-recommends \
        locales \
    && sed -i \
        -e '/en_US.UTF-8/s/^# //g' \
        -e '/fr_FR.UTF-8/s/^# //g' \
        /etc/locale.gen \
    && locale-gen \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# -------------------------------------------------------------------
# feature: build
# -------------------------------------------------------------------
# make, cmake and ninja are carried by every firmware variant, including the
# ones that do not use them: a few tens of MB against the 1.2 GB toolchain,
# not worth a separate variant.
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        ninja-build \
        git \
        wget \
        bzip2 \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: python
# -------------------------------------------------------------------
# The system interpreter, for scripts that expect /usr/bin/python3. Project
# environments are uv's job, hence no pip and no pipenv here.
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: uv
# -------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# wget, not curl: curl is only present in the dev variant. Piping the
# installer into sh would also hide a download failure, so download it, run
# it, then check that uv really is there.
RUN wget -qO /tmp/uv-install.sh https://astral.sh/uv/install.sh \
    && env UV_INSTALL_DIR=/usr/local/bin UV_NO_MODIFY_PATH=1 \
        sh /tmp/uv-install.sh \
    && rm /tmp/uv-install.sh \
    && uv --version

# -------------------------------------------------------------------
# feature: arm-none-eabi
# -------------------------------------------------------------------
# The expensive layer, 1.2 GB. It must stay after every feature it shares
# with the other variants, otherwise it is stored once per variant.
ARG ARM_TOOLCHAIN_VERSION=13.2.rel1
ARG ARM_DL_LINK=https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/${ARM_TOOLCHAIN_VERSION}/binrel/arm-gnu-toolchain-${ARM_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi.tar.xz

ENV ARM_TOOLCHAIN_DIR=/opt/gnu_arm/${ARM_TOOLCHAIN_VERSION}
ENV PATH=${ARM_TOOLCHAIN_DIR}/bin:$PATH
ENV AM_I_IN_A_DOCKER_CONTAINER=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        xz-utils \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${ARM_TOOLCHAIN_DIR} /tmp/arm-toolchain \
    && wget -qO- ${ARM_DL_LINK} | tar -xJ -C /tmp/arm-toolchain --strip-components=1 \
    && mv /tmp/arm-toolchain/* ${ARM_TOOLCHAIN_DIR} \
    && rm -rf /tmp/arm-toolchain

ENV TOOLCHAIN_DEVCONTAINER_DIR=${ARM_TOOLCHAIN_DIR}

# -------------------------------------------------------------------
# feature: ci-runtime
# -------------------------------------------------------------------
# What the Forgejo runner needs to execute a job inside this image, not what
# the projects need to build. The runner runs the JavaScript actions
# (actions/checkout and friends) with the node of the container, and clones
# over ssh, hence node, git and openssh-client.
# `file` is there for libmagic: reuse depends on it, and a REUSE lint is a CI
# job like any other.
RUN apt-get update && apt-get install -y --no-install-recommends \
        nodejs \
        npm \
        git \
        openssh-client \
        curl \
        ca-certificates \
        file \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: dev
# -------------------------------------------------------------------
# Ends on USER dev, so nothing can be stacked after it except a feature that
# switches back to root itself, the way `jlink` does. A CI variant built on
# top of this one would run as a non-root user and its apt-get would fail.
ARG USERNAME=dev

RUN apt-get update && apt-get install -y --no-install-recommends \
        sudo \
        udev \
        ssh \
        curl \
        bear \
        bash-completion \
        openocd \
        gdb-multiarch \
        iproute2 \
        usbutils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m ${USERNAME} \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" \
        > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME} \
    && usermod -a -G dialout,plugdev ${USERNAME} \
    && mkdir -p /home/${USERNAME}/project

LABEL maintainer="Pierre-Noel Bouteville <pnb990@gmail.com>" \
    description="Devcontainer image, interactive development and debugging"

USER ${USERNAME}
ENV SHELL=/bin/bash
CMD ["/bin/bash"]

# -------------------------------------------------------------------
# feature: jlink
# -------------------------------------------------------------------
# Kept out of `dev` and stacked after it, because SEGGER restricts the
# redistribution of this .deb: a variant carrying this feature must not be
# pushed to a public registry.
#
# `dev` hands over a non-root image, so switch back to root for the install
# and hand it back at the end. Stack this feature right after `dev`, nothing
# else creates the user it returns to.
ARG USERNAME=dev
USER root

# The postinst is removed because it only sets up udev rules and prompts,
# which cannot run during a build.
ARG JLINK_LINK="https://www.segger.com/downloads/jlink/JLink_Linux_V856_x86_64.deb"
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
        ca-certificates \
    && curl -L ${JLINK_LINK} \
        -d "accept_license_agreement=accepted" \
        -o /tmp/jlink.deb \
    && dpkg --unpack /tmp/jlink.deb \
    && rm /tmp/jlink.deb \
    && rm -f /var/lib/dpkg/info/jlink.postinst \
    && apt-get install -y --no-install-recommends --fix-broken \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER ${USERNAME}

# -------------------------------------------------------------------
# provenance
# -------------------------------------------------------------------
# Kept last in every image: IMAGE_COMMIT changes at every build, and an ARG
# read by a RUN invalidates that layer and everything after it. Last means
# the only rebuilt layer is this one, a few bytes.
#
# Written to a file, not only to a LABEL: a job running inside the container
# can read a file, it cannot read the labels of its own image. This is what
# makes a floating tag traceable -- the log of a green run says exactly which
# commit to pin when that build has to be rolled back to.
ARG IMAGE_COMMIT=unknown
LABEL org.opencontainers.image.revision="$IMAGE_COMMIT"
RUN printf 'image=%s\nvariant=%s\ncommit=%s\n' \
        'fw-arm-none-eabi-13.2.rel1' 'dev-jlink' "$IMAGE_COMMIT" \
        > /etc/pnb-image
