# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Generated by src/main.py from config/default/config.yaml.
# Do not edit by hand: edit ressources/templates/ and regenerate.
#
# image    : fw-arm-none-eabi-13.2.rel1
# variant  : dev-x11
# features : locale -> build -> python -> uv -> arm-13.2.rel1 -> ci-runtime -> dev -> x11

FROM debian:trixie-slim

# -------------------------------------------------------------------
# feature: locale
# -------------------------------------------------------------------
# Kept first in every variant of every image: it is the layer all the images
# share, so it must be identical everywhere.
RUN apt-get update && apt-get install -y --no-install-recommends \
        locales \
    && sed -i \
        -e '/en_US.UTF-8/s/^# //g' \
        -e '/fr_FR.UTF-8/s/^# //g' \
        /etc/locale.gen \
    && locale-gen \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# -------------------------------------------------------------------
# feature: build
# -------------------------------------------------------------------
# make, cmake and ninja are carried by every firmware variant, including the
# ones that do not use them: a few tens of MB against the 1.2 GB toolchain,
# not worth a separate variant.
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        ninja-build \
        git \
        wget \
        bzip2 \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: python
# -------------------------------------------------------------------
# The system interpreter, for scripts that expect /usr/bin/python3. Project
# environments are uv's job, hence no pip and no pipenv here.
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: uv
# -------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# wget, not curl: curl is only present in the dev variant. Piping the
# installer into sh would also hide a download failure, so download it, run
# it, then check that uv really is there.
RUN wget -qO /tmp/uv-install.sh https://astral.sh/uv/install.sh \
    && env UV_INSTALL_DIR=/usr/local/bin UV_NO_MODIFY_PATH=1 \
        sh /tmp/uv-install.sh \
    && rm /tmp/uv-install.sh \
    && uv --version

# -------------------------------------------------------------------
# feature: arm-none-eabi
# -------------------------------------------------------------------
# The expensive layer, 1.2 GB. It must stay after every feature it shares
# with the other variants, otherwise it is stored once per variant.
ARG ARM_TOOLCHAIN_VERSION=13.2.rel1
ARG ARM_DL_LINK=https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/${ARM_TOOLCHAIN_VERSION}/binrel/arm-gnu-toolchain-${ARM_TOOLCHAIN_VERSION}-x86_64-arm-none-eabi.tar.xz

ENV ARM_TOOLCHAIN_DIR=/opt/gnu_arm/${ARM_TOOLCHAIN_VERSION}
ENV PATH=${ARM_TOOLCHAIN_DIR}/bin:$PATH
ENV AM_I_IN_A_DOCKER_CONTAINER=1

RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        xz-utils \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p ${ARM_TOOLCHAIN_DIR} /tmp/arm-toolchain \
    && wget -qO- ${ARM_DL_LINK} | tar -xJ -C /tmp/arm-toolchain --strip-components=1 \
    && mv /tmp/arm-toolchain/* ${ARM_TOOLCHAIN_DIR} \
    && rm -rf /tmp/arm-toolchain

ENV TOOLCHAIN_DEVCONTAINER_DIR=${ARM_TOOLCHAIN_DIR}

# -------------------------------------------------------------------
# feature: ci-runtime
# -------------------------------------------------------------------
# What the Forgejo runner needs to execute a job inside this image, not what
# the projects need to build. The runner runs the JavaScript actions
# (actions/checkout and friends) with the node of the container, and clones
# over ssh, hence node, git and openssh-client.
# `file` is there for libmagic: reuse depends on it, and a REUSE lint is a CI
# job like any other.
RUN apt-get update && apt-get install -y --no-install-recommends \
        nodejs \
        npm \
        git \
        openssh-client \
        curl \
        ca-certificates \
        file \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: dev
# -------------------------------------------------------------------
# Ends on USER dev, so nothing can be stacked after it except a feature that
# switches back to root itself, the way `jlink` does. A CI variant built on
# top of this one would run as a non-root user and its apt-get would fail.
ARG USERNAME=dev

RUN apt-get update && apt-get install -y --no-install-recommends \
        sudo \
        udev \
        ssh \
        curl \
        bear \
        bash-completion \
        openocd \
        gdb-multiarch \
        iproute2 \
        usbutils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m ${USERNAME} \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" \
        > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME} \
    && usermod -a -G dialout,plugdev ${USERNAME} \
    && mkdir -p /home/${USERNAME}/project

LABEL maintainer="Pierre-Noel Bouteville <pnb990@gmail.com>" \
    description="Devcontainer image, interactive development and debugging"

USER ${USERNAME}
ENV SHELL=/bin/bash
CMD ["/bin/bash"]

# -------------------------------------------------------------------
# feature: x11
# -------------------------------------------------------------------
# What a GUI tool of the projects needs to draw on the X server of the host,
# the simulation panel of pnbchrono (tools/sim_panel.py) first. The container
# is an X *client* only: no server, no window manager, the display comes from
# the host through $DISPLAY and the socket bind-mounted by the devcontainer.
#
# python3-tk is the point of this feature. Debian splits tkinter out of the
# `python3` package because _tkinter drags in Tcl/Tk and X11, which a server
# or a CI image has no use for, so `import tkinter` fails on our `python`
# feature alone. It cannot be installed from PyPI either: it is a C extension
# of the standard library, bound to the interpreter that Debian built.
#
# xauth is not optional: with `ssh -X` or a devcontainer forwarding a cookie,
# the X connection is refused without it, and the failure reads as a plain
# "cannot connect to display".
#
# x11-apps is 3 MB and carries xeyes, which answers "is the display reachable
# at all" without involving python, tkinter or the project. Worth those 3 MB
# the first time a DISPLAY does not work.
#
# The whole feature is 11 MB on top of `python`. What it leaves out is Qt:
# PySide6 and PyQt need libGL and libEGL, and the mesa stack behind them is
# 75 MB before a single Qt library is installed. That belongs to the `pyqt6`
# feature, stacked on top of this one, so that a devcontainer running the
# simulation panel does not carry it.
#
# Stacked after `dev`, which hands over a non-root image, so this feature
# switches back to root itself and returns to the user `dev` created. It is
# the same contract as `jlink`, and the same constraint: it must not be
# placed before a feature that expects to run as root.
ARG USERNAME=dev
USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3-tk \
        xauth \
        x11-apps \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

LABEL description="Devcontainer image with an X11 client stack and tkinter"

USER ${USERNAME}

# -------------------------------------------------------------------
# provenance
# -------------------------------------------------------------------
# Kept last in every image: IMAGE_COMMIT changes at every build, and an ARG
# read by a RUN invalidates that layer and everything after it. Last means
# the only rebuilt layer is this one, a few bytes.
#
# Written to a file, not only to a LABEL: a job running inside the container
# can read a file, it cannot read the labels of its own image. This is what
# makes a floating tag traceable -- the log of a green run says exactly which
# commit to pin when that build has to be rolled back to.
#
# /etc/image-info, and the shape of os-release and machine-info: quoted
# KEY="value" lines, so the file is both readable with `cat` and sourceable
# with `. /etc/image-info`. Not /etc/*-release, which is the legacy
# distro-identification pile os-release was written to replace, and not
# os-release itself -- that is a symlink into /usr/lib owned by the base
# distribution, and appending to it means either editing the vendor's file or
# breaking the link.
#
# The keys are prefixed. A bare COMMIT= would collide with a local of whatever
# script sources this. IMAGE_ID and IMAGE_VERSION are avoided on purpose: they
# are os-release spec names with defined meanings, and borrowing them for
# something else is worse than not using them.
#
# `dev` hands over a non-root image, and /etc is only writable by root, so
# switch back for this layer and hand the image back the way `dev` left it.
# `jlink` returns to the user `dev` created, so testing `dev` covers it too.
USER root
ARG IMAGE_COMMIT=unknown
LABEL org.opencontainers.image.revision="$IMAGE_COMMIT"
RUN printf 'IMAGE_NAME="%s"\nIMAGE_VARIANT="%s"\nIMAGE_COMMIT="%s"\n' \
        'fw-arm-none-eabi-13.2.rel1' 'dev-x11' "$IMAGE_COMMIT" \
        > /etc/image-info
USER ${USERNAME}
