# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Generated by src/main.py from config/default/config.yaml.
# Do not edit by hand: edit ressources/templates/ and regenerate.
#
# image    : node
# variant  : dev
# features : locale -> node -> ci-runtime -> build -> dev -> new_git

FROM debian:trixie-slim

# -------------------------------------------------------------------
# feature: locale
# -------------------------------------------------------------------
# Kept first in every variant of every image: it is the layer all the images
# share, so it must be identical everywhere.
RUN apt-get update && apt-get install -y --no-install-recommends \
        locales \
    && sed -i \
        -e '/en_US.UTF-8/s/^# //g' \
        -e '/fr_FR.UTF-8/s/^# //g' \
        /etc/locale.gen \
    && locale-gen \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# -------------------------------------------------------------------
# feature: node
# -------------------------------------------------------------------
# A current Node LTS, plus the TypeScript and VS Code extension tooling
# installed globally. Debian trixie ships Node 20, out of support since
# April 2026, and @vscode/vsce already requires Node >= 22.
#
# The official tarball, not NodeSource: no third-party apt repository to
# trust, and the checksum below is checked against nodejs.org's own list.
# Installed into /usr/local, which precedes /usr/bin on PATH, so it shadows
# the apt node that `ci-runtime` may bring without conflicting with it. Same
# approach as `new_git`.
#
# The global tools are for one-off use and quick checks; a project still pins
# its own copies in package-lock.json and runs those through `npm ci`.
ARG NODE_VERSION=24.21.0
ARG TYPESCRIPT_VERSION=7.0.2
ARG TSX_VERSION=4.23.15
ARG VSCE_VERSION=4.0.0

RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        xz-utils \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN case "$(dpkg --print-architecture)" in \
        amd64) NODE_ARCH=x64 ;; \
        arm64) NODE_ARCH=arm64 ;; \
        *) echo "unsupported architecture" >&2; exit 1 ;; \
    esac \
    && NODE_TARBALL="node-v${NODE_VERSION}-linux-${NODE_ARCH}.tar.xz" \
    && cd /tmp \
    && wget -q "https://nodejs.org/dist/v${NODE_VERSION}/${NODE_TARBALL}" \
    && wget -q "https://nodejs.org/dist/v${NODE_VERSION}/SHASUMS256.txt" \
    && grep " ${NODE_TARBALL}\$" SHASUMS256.txt | sha256sum -c - \
    && tar -xJf "${NODE_TARBALL}" -C /usr/local \
        --strip-components=1 --no-same-owner \
        --exclude='*/CHANGELOG.md' --exclude='*/README.md' \
        --exclude='*/LICENSE' --exclude='*/doc' \
    && rm -f "${NODE_TARBALL}" SHASUMS256.txt \
    && node --version \
    && npm --version

RUN npm install -g \
        "typescript@${TYPESCRIPT_VERSION}" \
        "tsx@${TSX_VERSION}" \
        "@vscode/vsce@${VSCE_VERSION}" \
    && npm cache clean --force \
    && tsc --version \
    && tsx --version \
    && vsce --version

# -------------------------------------------------------------------
# feature: ci-runtime
# -------------------------------------------------------------------
# What the Forgejo runner needs to execute a job inside this image, not what
# the projects need to build. The runner runs the JavaScript actions
# (actions/checkout and friends) with the node of the container, and clones
# over ssh, hence node, git and openssh-client.
# `file` is there for libmagic: reuse depends on it, and a REUSE lint is a CI
# job like any other.
RUN apt-get update && apt-get install -y --no-install-recommends \
        nodejs \
        npm \
        git \
        openssh-client \
        curl \
        ca-certificates \
        file \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: build
# -------------------------------------------------------------------
# make, cmake and ninja are carried by every firmware variant, including the
# ones that do not use them: a few tens of MB against the 1.2 GB toolchain,
# not worth a separate variant.
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        cmake \
        ninja-build \
        git \
        wget \
        bzip2 \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: dev
# -------------------------------------------------------------------
# Ends on USER dev, so nothing can be stacked after it except a feature that
# switches back to root itself, the way `jlink` does. A CI variant built on
# top of this one would run as a non-root user and its apt-get would fail.
ARG USERNAME=dev

RUN apt-get update && apt-get install -y --no-install-recommends \
        sudo \
        udev \
        ssh \
        curl \
        bear \
        bash-completion \
        openocd \
        gdb-multiarch \
        iproute2 \
        usbutils \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m ${USERNAME} \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" \
        > /etc/sudoers.d/${USERNAME} \
    && chmod 0440 /etc/sudoers.d/${USERNAME} \
    && usermod -a -G dialout,plugdev ${USERNAME} \
    && mkdir -p /home/${USERNAME}/project

LABEL maintainer="Pierre-Noel Bouteville <pnb990@gmail.com>" \
    description="Devcontainer image, interactive development and debugging"

USER ${USERNAME}
ENV SHELL=/bin/bash
CMD ["/bin/bash"]

# -------------------------------------------------------------------
# feature: new_git
# -------------------------------------------------------------------
# A newer git (>= 2.48) built from source, for relative-path git worktree
# linking: worktrees keep working when the whole tree is relocated (e.g. the
# repo is bind-mounted at a different path in a container). Debian trixie ships
# git 2.47, which lacks it.
#
# Built into /usr/local, which precedes /usr/bin on PATH, so it shadows the apt
# package without removing it (still needed for git-gui/gitk).
#
# Stacked after `dev`, which hands over a non-root image, so this feature
# switches back to root itself and returns to the user `dev` created. Same
# contract as `clang` and `jlink`.
ARG USERNAME=dev
ARG GIT_VERSION=2.53.0
USER root

# Build dependencies for git: compiler/make, plus curl (remote transport),
# openssl (https/crypto) and zlib (packfile compression). NO_GETTEXT,
# NO_TCLTK, NO_EXPAT and NO_RUST below drop the matching dependencies.
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        libcurl4-openssl-dev \
        libssl-dev \
        zlib1g-dev \
        wget \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget https://www.kernel.org/pub/software/scm/git/git-${GIT_VERSION}.tar.gz \
        -O /tmp/git-${GIT_VERSION}.tar.gz \
    && tar -xzf /tmp/git-${GIT_VERSION}.tar.gz -C /tmp \
    && cd /tmp/git-${GIT_VERSION} \
    && make -j"$(nproc)" \
        NO_GETTEXT=1 NO_TCLTK=1 NO_EXPAT=1 NO_RUST=1 prefix=/usr/local all \
    && make \
        NO_GETTEXT=1 NO_TCLTK=1 NO_EXPAT=1 NO_RUST=1 prefix=/usr/local install \
    && rm -f /tmp/git-${GIT_VERSION}.tar.gz \
    && rm -rf /tmp/git-${GIT_VERSION}

USER ${USERNAME}

# -------------------------------------------------------------------
# provenance
# -------------------------------------------------------------------
# Kept last in every image: IMAGE_COMMIT changes at every build, and an ARG
# read by a RUN invalidates that layer and everything after it. Last means
# the only rebuilt layer is this one, a few bytes.
#
# Written to a file, not only to a LABEL: a job running inside the container
# can read a file, it cannot read the labels of its own image. This is what
# makes a floating tag traceable -- the log of a green run says exactly which
# commit to pin when that build has to be rolled back to.
#
# /etc/image-info, and the shape of os-release and machine-info: quoted
# KEY="value" lines, so the file is both readable with `cat` and sourceable
# with `. /etc/image-info`. Not /etc/*-release, which is the legacy
# distro-identification pile os-release was written to replace, and not
# os-release itself -- that is a symlink into /usr/lib owned by the base
# distribution, and appending to it means either editing the vendor's file or
# breaking the link.
#
# The keys are prefixed. A bare COMMIT= would collide with a local of whatever
# script sources this. IMAGE_ID and IMAGE_VERSION are avoided on purpose: they
# are os-release spec names with defined meanings, and borrowing them for
# something else is worse than not using them.
#
# `dev` hands over a non-root image, and /etc is only writable by root, so
# switch back for this layer and hand the image back the way `dev` left it.
# `jlink` returns to the user `dev` created, so testing `dev` covers it too.
USER root
ARG IMAGE_COMMIT=unknown
# The commit's own date, RFC 3339, not the build time -- a build time would
# change on every rebuild and destroy the property IMAGE_COMMIT exists for.
# It is here because a hash has no order: it answers "which build is this",
# never "is this older than what I have pinned". The image tag carries the
# same date in its compact YYYYMMDD form, which is what makes two pins
# comparable by eye; this one is the full value, so that
# org.opencontainers.image.created below is what the OCI spec says it is.
ARG IMAGE_DATE=unknown
LABEL org.opencontainers.image.revision="$IMAGE_COMMIT"
LABEL org.opencontainers.image.created="$IMAGE_DATE"
RUN printf 'IMAGE_NAME="%s"\nIMAGE_VARIANT="%s"\nIMAGE_COMMIT="%s"\nIMAGE_DATE="%s"\n' \
        'node' 'dev' "$IMAGE_COMMIT" "$IMAGE_DATE" \
        > /etc/image-info
USER ${USERNAME}
