# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Generated by src/main.py from config/default/config.yaml.
# Do not edit by hand: edit ressources/templates/ and regenerate.
#
# image    : node
# variant  : base
# features : locale -> node

FROM debian:trixie-slim

# -------------------------------------------------------------------
# feature: locale
# -------------------------------------------------------------------
# Kept first in every variant of every image: it is the layer all the images
# share, so it must be identical everywhere.
RUN apt-get update && apt-get install -y --no-install-recommends \
        locales \
    && sed -i \
        -e '/en_US.UTF-8/s/^# //g' \
        -e '/fr_FR.UTF-8/s/^# //g' \
        /etc/locale.gen \
    && locale-gen \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# -------------------------------------------------------------------
# feature: node
# -------------------------------------------------------------------
# A current Node LTS, plus the TypeScript and VS Code extension tooling
# installed globally. Debian trixie ships Node 20, out of support since
# April 2026, and @vscode/vsce already requires Node >= 22.
#
# The official tarball, not NodeSource: no third-party apt repository to
# trust, and the checksum below is checked against nodejs.org's own list.
# Installed into /usr/local, which precedes /usr/bin on PATH, so it shadows
# the apt node that `ci-runtime` may bring without conflicting with it. Same
# approach as `new_git`.
#
# The global tools are for one-off use and quick checks; a project still pins
# its own copies in package-lock.json and runs those through `npm ci`.
ARG NODE_VERSION=24.21.0
ARG TYPESCRIPT_VERSION=7.0.2
ARG TSX_VERSION=4.23.15
ARG VSCE_VERSION=4.0.0

RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        xz-utils \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN case "$(dpkg --print-architecture)" in \
        amd64) NODE_ARCH=x64 ;; \
        arm64) NODE_ARCH=arm64 ;; \
        *) echo "unsupported architecture" >&2; exit 1 ;; \
    esac \
    && NODE_TARBALL="node-v${NODE_VERSION}-linux-${NODE_ARCH}.tar.xz" \
    && cd /tmp \
    && wget -q "https://nodejs.org/dist/v${NODE_VERSION}/${NODE_TARBALL}" \
    && wget -q "https://nodejs.org/dist/v${NODE_VERSION}/SHASUMS256.txt" \
    && grep " ${NODE_TARBALL}\$" SHASUMS256.txt | sha256sum -c - \
    && tar -xJf "${NODE_TARBALL}" -C /usr/local \
        --strip-components=1 --no-same-owner \
        --exclude='*/CHANGELOG.md' --exclude='*/README.md' \
        --exclude='*/LICENSE' --exclude='*/doc' \
    && rm -f "${NODE_TARBALL}" SHASUMS256.txt \
    && node --version \
    && npm --version

RUN npm install -g \
        "typescript@${TYPESCRIPT_VERSION}" \
        "tsx@${TSX_VERSION}" \
        "@vscode/vsce@${VSCE_VERSION}" \
    && npm cache clean --force \
    && tsc --version \
    && tsx --version \
    && vsce --version

# -------------------------------------------------------------------
# provenance
# -------------------------------------------------------------------
# Kept last in every image: IMAGE_COMMIT changes at every build, and an ARG
# read by a RUN invalidates that layer and everything after it. Last means
# the only rebuilt layer is this one, a few bytes.
#
# Written to a file, not only to a LABEL: a job running inside the container
# can read a file, it cannot read the labels of its own image. This is what
# makes a floating tag traceable -- the log of a green run says exactly which
# commit to pin when that build has to be rolled back to.
#
# /etc/image-info, and the shape of os-release and machine-info: quoted
# KEY="value" lines, so the file is both readable with `cat` and sourceable
# with `. /etc/image-info`. Not /etc/*-release, which is the legacy
# distro-identification pile os-release was written to replace, and not
# os-release itself -- that is a symlink into /usr/lib owned by the base
# distribution, and appending to it means either editing the vendor's file or
# breaking the link.
#
# The keys are prefixed. A bare COMMIT= would collide with a local of whatever
# script sources this. IMAGE_ID and IMAGE_VERSION are avoided on purpose: they
# are os-release spec names with defined meanings, and borrowing them for
# something else is worse than not using them.
ARG IMAGE_COMMIT=unknown
# The commit's own date, RFC 3339, not the build time -- a build time would
# change on every rebuild and destroy the property IMAGE_COMMIT exists for.
# It is here because a hash has no order: it answers "which build is this",
# never "is this older than what I have pinned". The image tag carries the
# same date in its compact YYYYMMDD form, which is what makes two pins
# comparable by eye; this one is the full value, so that
# org.opencontainers.image.created below is what the OCI spec says it is.
ARG IMAGE_DATE=unknown
LABEL org.opencontainers.image.revision="$IMAGE_COMMIT"
LABEL org.opencontainers.image.created="$IMAGE_DATE"
RUN printf 'IMAGE_NAME="%s"\nIMAGE_VARIANT="%s"\nIMAGE_COMMIT="%s"\nIMAGE_DATE="%s"\n' \
        'node' 'base' "$IMAGE_COMMIT" "$IMAGE_DATE" \
        > /etc/image-info
