# SPDX-FileCopyrightText: 2025 Pierre-Noel Bouteville  <pnb990@gmail.com>
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Generated by src/main.py from config/default/config.yaml.
# Do not edit by hand: edit ressources/templates/ and regenerate.
#
# image    : python3
# variant  : base
# features : locale -> python -> uv

FROM debian:trixie-slim

# -------------------------------------------------------------------
# feature: locale
# -------------------------------------------------------------------
# Kept first in every variant of every image: it is the layer all the images
# share, so it must be identical everywhere.
RUN apt-get update && apt-get install -y --no-install-recommends \
        locales \
    && sed -i \
        -e '/en_US.UTF-8/s/^# //g' \
        -e '/fr_FR.UTF-8/s/^# //g' \
        /etc/locale.gen \
    && locale-gen \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    LC_ALL=en_US.UTF-8

# -------------------------------------------------------------------
# feature: python
# -------------------------------------------------------------------
# The system interpreter, for scripts that expect /usr/bin/python3. Project
# environments are uv's job, hence no pip and no pipenv here.
RUN apt-get update && apt-get install -y --no-install-recommends \
        python3 \
        python3-venv \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# -------------------------------------------------------------------
# feature: uv
# -------------------------------------------------------------------
RUN apt-get update && apt-get install -y --no-install-recommends \
        wget \
        ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# wget, not curl: curl is only present in the dev variant. Piping the
# installer into sh would also hide a download failure, so download it, run
# it, then check that uv really is there.
RUN wget -qO /tmp/uv-install.sh https://astral.sh/uv/install.sh \
    && env UV_INSTALL_DIR=/usr/local/bin UV_NO_MODIFY_PATH=1 \
        sh /tmp/uv-install.sh \
    && rm /tmp/uv-install.sh \
    && uv --version

# -------------------------------------------------------------------
# provenance
# -------------------------------------------------------------------
# Kept last in every image: IMAGE_COMMIT changes at every build, and an ARG
# read by a RUN invalidates that layer and everything after it. Last means
# the only rebuilt layer is this one, a few bytes.
#
# Written to a file, not only to a LABEL: a job running inside the container
# can read a file, it cannot read the labels of its own image. This is what
# makes a floating tag traceable -- the log of a green run says exactly which
# commit to pin when that build has to be rolled back to.
ARG IMAGE_COMMIT=unknown
LABEL org.opencontainers.image.revision="$IMAGE_COMMIT"
RUN printf 'image=%s\nvariant=%s\ncommit=%s\n' \
        'python3' 'base' "$IMAGE_COMMIT" \
        > /etc/pnb-image
